### ISSUE TITLE
SSWPeople page include invalid URL in the <head>

### ISSUE THREAD

**Issue by nvhoanganh** [SSWConsulting/SSW.People.Profiles#138]
The following links are pointing to invalid resources:
href="/manifest.json"
href="/ssw/include/pigeon/img/apple-touch-icon-167x167.png" 
href="https://ssw.com.au/people/people/<PAGE_NAME>" eg. https://ssw.com.au/people/people/adam-cogan

**Comment by william-liebenberg** [comment]
@christianmorfordwaitessw can you take a look at this issue.

**Comment by christianmorfordwaitessw** [comment]
@nvhoanganh @william-liebenberg 
Done - Invalid links fixed

**Comment by tiagov8** [comment]
Hey @christianmorfordwaitessw 

CodeAuditor caught this manifest.json broken link
https://codeauditor.com/build/df9b58f3-3589-4c1a-2eb0-ab5b07cffed3

<img width="1210" alt="Screenshot 2023-05-05 at 1 03 56 PM" src="https://user-images.githubusercontent.com/12601228/236509473-b71681d9-30fd-461c-b57c-d39c6d680c3d.png">

1. Please investigate and fix
