### ISSUE TITLE
GitHub - Security on SSW People Wiki

### ISSUE THREAD

**Issue by rubycogan** [SSWConsulting/SSW.People.Profiles#238]
Hi Christian
https://github.com/SSWConsulting/SSW.People.Profiles/wiki 
I’ve was looking at the SSW People Wiki as requested by @adamcogan and I noticed a problem with the text so I went in to see if I could fix it. To my surprise, I was successful in making a change that went live. But I don’t have any permissions and I’m not a member of the SSW organisation yet 

1. Is this correct and by design?

| Ruby |

**Comment by christianmorfordwaitessw** [comment]
Hi Ruby,

Thank you for discovering this issue.

	1. Is this correct and by design?
No – This should be restricted to only users with write access.
I have updated the security policy to prevent the Wiki being edited by the public.

-Christian
