### ISSUE TITLE
Wiki - 5 Editing Profiles: Using Markdown

### ISSUE THREAD

**Issue by SSWnathanmills** [SSWConsulting/SSW.People.Profiles#263]
Hi,

The content in the Wiki is great! I noticed that under the Editing Profiles page in the Index there is a header called "Using Markdown" but there is not a section of the Editing Profiles page with the same title.

The other section on that page, Main Widget, when clicked takes the user to a specific point in the page but the Using Markdown one does not. Should the Using Markdown label in the Index be removed?

**Comment by christianmorfordwaitessw** [comment]
Hi @SSWnathanmills 

Thanks for discovering this issue.
**Done** - I've removed the extra Using Markdown link under Editing Profiles
![image](https://user-images.githubusercontent.com/56522256/87735529-19c06c00-c819-11ea-85e8-19b37004a1d0.png)
**Figure: Extra Using Markdown Link removed from the menu**
