### ISSUE TITLE
Image Update

### ISSUE THREAD

**Issue by StevenA89** [SSWConsulting/SSW.People.Profiles#268]
On the following page https://github.com/SSWConsulting/SSW.People.Profiles/wiki/4.-Creating-Profiles the clone repository image has the "3" under the highlighted box.
![2020-07-17_8-43-33](https://user-images.githubusercontent.com/20941002/87729873-aebb6900-c809-11ea-8aa3-a37742e41f8c.png)

**Comment by christianmorfordwaitessw** [comment]
Hi @StevenA89 
Thanks for spotting this
**Done** - I have fixed the image so that the 3 is over the red box
![image](https://user-images.githubusercontent.com/56522256/87736395-59885300-c81b-11ea-84a6-745384d158e7.png)
**Figure: The 3 is now over the red box**
