### ISSUE TITLE
Wiki - Quick Edits

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.People.Profiles#285]
Hey @christianmorfordwaitessw 
cc @SebastienBoissiere @adamcogan 

On https://github.com/SSWConsulting/SSW.People.Profiles/wiki/1.-Quick-Edits, there is no mention on who should be a reviewer (I know that it suggests @christianmorfordwaitessw).

I think it would be a good idea to assign suggestions to the page/profile owner
i.e. When I submit a PR for Adam's page, I want him to accept the changes because it is his profile and is the SME.

The only side effect I can foresee is that this change will require all SSW employees to have write permissions on the profiles repo. Although this shouldn't be a concern as we have branch protection on ```main```

Since this is a larger change than just updating the wiki, I'm looking for consensus first. What are your thoughts?

**Comment by christianmorfordwaitessw** [comment]
Hi @wicksipedia ,
cc @SebastienBoissiere  @adamcogan 

I think this is a good idea adding the person that owns the profile as a reviewer. I'll add instructions to the Wiki about adding mentions and reviewers to the pull request.

We are looking into how we can automatically notify in case someone forgets to add the mention/reviewer on Issue #322

We have given all SSW Employees write permissions to the repo, which helps solve this problem.

**Comment by christianmorfordwaitessw** [comment]
Hi @wicksipedia,
cc: @SebastienBoissiere @adamcogan 

> I'll add instructions to the Wiki about adding mentions and reviewers to the pull request.  

**Done** - Instructions have been added to the Wiki on [Quick Edits](https://github.com/SSWConsulting/SSW.People.Profiles/wiki/1.-Quick-Edits)
![image](https://user-images.githubusercontent.com/56522256/93832896-70836f80-fcba-11ea-89d5-e7f733f84ae6.png)
**Figure: Wiki instructions about adding reviewers to pull requests**

> We are looking into how we can automatically notify in case someone forgets to add the mention/reviewer on Issue #322  

**Done** -  People are automatically assigned as a reviewer to the PR when their profile is modified.
Video about this feature can be found at https://www.youtube.com/watch?v=_gz-NiluO0Y
