### ISSUE TITLE
Wiki | Looking for document on how to add curated videos

### ISSUE THREAD

**Issue by christoment** [SSWConsulting/SSW.People.Profiles#291]
I can't seem to find the instruction on how to add the YouTube video like shown in the picture below.

![image](https://user-images.githubusercontent.com/35278147/87736527-b1bf5500-c81b-11ea-9ed9-ae7ca95a6059.png)
Figure: YouTube contribution graph

**Comment by christianmorfordwaitessw** [comment]
Hi @christoment,

**Done** - See Wiki section https://github.com/SSWConsulting/SSW.People.Profiles/wiki/6.-Extras-%E2%80%90-Editing-profiles#extra---youtube-widget

I have added more steps and screenshots to the Wiki for adding the YouTube playlist widget.
![image](https://user-images.githubusercontent.com/56522256/88245480-b59b1d80-ccda-11ea-83cd-151784d6b381.png)
**Figure: Added more instructions to the Wiki around adding a YouTube playlist widget**
