### ISSUE TITLE
SSW People should have an executive overview

### ISSUE THREAD

**Issue by miichaelsmedley** [SSWConsulting/SSW.People.Profiles#296]
SSW People is great but in the Introduction, we should elaborate on why we did this and what problem it solves. It needs a paragraph executive summary.

**Comment by christianmorfordwaitessw** [comment]
Hi @miichaelsmedley,

As per our conversation, I have added the URL to Adam's blog about why we created SSW People and the YouTube video on why we chose GitHub as out back end.

https://github.com/SSWConsulting/SSW.People.Profiles/wiki
https://github.com/SSWConsulting/SSW.People/wiki

![image](https://user-images.githubusercontent.com/56522256/88364445-47338980-cdc6-11ea-85ad-ea0d78312379.png)
**Figure: Added links to Adam's blog and video to explain the reason behind SSW People.**
