### ISSUE TITLE
Wiki - Home- Missing link for Youtube Contribution graph

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.People.Profiles#297]
On the [Home](https://github.com/SSWConsulting/SSW.People.Profiles/wiki) of the wiki on the bottom, we are listing additional widgets.

The "Youtube Contribution graph" doesn't have a separate Wiki page while "Youtube widget" has.

![image](https://user-images.githubusercontent.com/5943653/87737771-3790cf80-c81f-11ea-8dd2-632d7b4be418.png)

**Comment by christianmorfordwaitessw** [comment]
Hi @jernejk,

> The "Youtube Contribution graph" doesn't have a separate Wiki page while "Youtube widget" has.

**Done** - See https://github.com/SSWConsulting/SSW.People.Profiles/wiki
This was meant to be the GitHub Contributions widget, so I have fixed the typo as well.
The instructions for adding the GitHub Contributions widget can be found on this [page](https://github.com/SSWConsulting/SSW.People.Profiles/wiki/6.-Extras-%E2%80%90-Editing-profiles#extra---gitHub-contributions-widget) 
![image](https://user-images.githubusercontent.com/56522256/88245699-7e793c00-ccdb-11ea-99dd-851640bce3d5.png)
**Figure: GitHub Contributions widget now has a link to its own section in the Wiki**
