### ISSUE TITLE
Can't find the youtubePlayListId in people's profile

### ISSUE THREAD

**Issue by jerryluossw** [SSWConsulting/SSW.People.Profiles#309]
As per video [https://www.youtube.com/watch?v=M3Y1psUzTZo](https://www.youtube.com/watch?v=M3Y1psUzTZo), we can add a YouTube Playlist in our profile, but I can't find it in all people's profiles.

![01](https://user-images.githubusercontent.com/68266237/87742707-dfa39a00-c819-11ea-9ac5-5a4c289184c2.png)
**Figure: The video shows that we can add youtubePllayListId**

![02](https://user-images.githubusercontent.com/68266237/87742875-3dd07d00-c81a-11ea-9fa1-df02e5b279c2.png)
**Figure: Can't find youtubePllayListId in JK's profile**

**Comment by christianmorfordwaitessw** [comment]
Hi @jerryluossw,

> As per video https://www.youtube.com/watch?v=M3Y1psUzTZo, we can add a YouTube Playlist in our profile, but I can't find it in all people's profiles.

The YouTube playlist ID needs to be added to CRM which is in the description on the video, but it's not obvious and is easily missed. 
I have added more steps and screenshots to the Wiki, does this make it clearer?

See this page https://github.com/SSWConsulting/SSW.People.Profiles/wiki/6.-Extras-%E2%80%90-Editing-profiles#extra---youtube-widget

![image](https://user-images.githubusercontent.com/56522256/88245152-67394f00-ccd9-11ea-8b3e-e97a490258cb.png)
**Figure: Wiki instructions for adding the YouTube Playlist ID into Dynamics CRM**
