### ISSUE TITLE
You have Scrum twice in your list of skills

### ISSUE THREAD

**Issue by PennyWalker** [SSWConsulting/SSW.People.Profiles#310]
Hi Mike, I would suggest updating your skills - it has Scrum there twice.

**Comment by christianmorfordwaitessw** [comment]
Hi @PennyWalker, 
cc @miichaelsmedley @adamcogan 

This information comes from CRM and needs to be edited there.
1. Can you please update CRM and removed Michaels profile
2. Check that the Wiki documentation is clear enough about how some profile data comes from markdown and how other data comes from CRM.

**Comment by PennyWalker** [comment]
*   Can you please update CRM and removed Michaels profile
Done. Removed.


  *   Check that the Wiki documentation is clear enough about how some profile data comes from markdown and how other data comes from CRM.
Done, yes it is clear. I was already aware when I lodged the issue, but Adam wanted us to test Github. 😊
Penny
