### ISSUE TITLE
Wiki - use emojis on all possible widgets

### ISSUE THREAD

**Issue by PennyWalker** [SSWConsulting/SSW.People.Profiles#312]

**Comment by christianmorfordwaitessw** [comment]
Hi @PennyWalker,

**Done** - see https://github.com/SSWConsulting/SSW.People.Profiles/wiki

![image](https://user-images.githubusercontent.com/56522256/88493574-29983700-cff5-11ea-8dc3-7a934fa66f37.png)
**Figure: Added emojis to all widgets**
