### ISSUE TITLE
Can we have more detail in social weight section?

### ISSUE THREAD

**Issue by VictorYMH** [SSWConsulting/SSW.People.Profiles#317]
more detail about how to add/update social media information

**Comment by christianmorfordwaitessw** [comment]
Hi @VictorYMH,

**Done** - see this page https://github.com/SSWConsulting/SSW.People.Profiles/wiki/3.-Updating-CRM#social-widget
I have added more screenshots in the Wiki for updating the social links in Dynamics CRM.

![image](https://user-images.githubusercontent.com/56522256/88244527-75866b80-ccd7-11ea-9d11-b6eea2f8e841.png)
**Figure: Instructions for adding social links into CRM**
