### ISSUE TITLE
Editing profiles

### ISSUE THREAD

**Issue by AnkyChe** [SSWConsulting/SSW.People.Profiles#320]
For the Your .md file figure, highlight the green part which should not be deleted.

**Comment by christianmorfordwaitessw** [comment]
Hi @AnkyChe,

**Done** - See this page https://github.com/SSWConsulting/SSW.People.Profiles/wiki/4.-Creating-profiles
I have updated the wording about the green bar indicating which part should not be deleted.
Does this make it clearer?  

![image](https://user-images.githubusercontent.com/56522256/88241533-b4172880-cccd-11ea-871a-da8dda63c50c.png)
**Figure: Updated instructions about green bar indicating which part should not be deleted**
