### ISSUE TITLE
Profile - Investigate how to notify Jason if someone modify his profile

### ISSUE THREAD

**Issue by SebastienBoissiere** [SSWConsulting/SSW.People.Profiles#322]
As per our conversation with @adamcogan and @ozdemir-mehmet, 
if someone modify Jason's profile, Jason is not notified.
Investigate how to notify Jason when someone modify his profile.

**Comment by christianmorfordwaitessw** [comment]
Hi @adamcogan,

**Done** - People are automatically assigned as a reviewer to the PR when their profile is modified.

video about this feature can be found at https://www.youtube.com/watch?v=_gz-NiluO0Y
