### ISSUE TITLE
Add Field to CRM for public photo album URL

### ISSUE THREAD

**Issue by BrandlD** [SSWConsulting/SSW.People.Profiles#336]
Hi @SebastienBoissiere @ozdemir-mehmet @calumjs @christianmorfordwaitessw  ,

as per my conversation with Seb & @adamcogan  could you please create a new field for each SSW employee in CRM to link up their public photo album on the SSWPeople page

See the example of Adam Cogan:  https://photos.app.goo.gl/ykxNnuwwMRNE1nrw7

 1. Add a new field to CRM - Public Photo Album URL
 
-d

**Comment by SebastienBoissiere** [comment]
Hi @BrandlD 
CC @adamcogan 

**Done**, this closes #336

The field has been added to CRM.
![image](https://user-images.githubusercontent.com/28290353/88498048-6bc97480-d005-11ea-8a87-8577c595c688.png)
**Figure: the field 'Public Photo Album URL' has been added to CRM**
