### ISSUE TITLE
Be able to add embedded tweets to profiles

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People.Profiles#400]
Hi @SebastienBoissiere 

We would like to add embedded tweets to SSW People Profiles
 

E.g. Add this one to JK's profile:
[https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FSSW_TV%2Fstatus%2F1317996770069147648&widget=Tweet](https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2FSSW_TV%2Fstatus%2F1317996770069147648&widget=Tweet)

The code is like this:

`blockquote class="twitter-tweet"><p lang="en" dir="ltr">Congratulations to SSW Software Architect <a href="https://twitter.com/jernej_kavka?ref_src=twsrc%5Etfw">@jernej_kavka</a> (JK) who is now a <a href="https://twitter.com/hashtag/MicrosoftMVP?src=hash&amp;ref_src=twsrc%5Etfw">#MicrosoftMVP</a> for <a href="https://twitter.com/hashtag/AI?src=hash&amp;ref_src=twsrc%5Etfw">#AI</a>. 🎉<br><br>JK has helped other developers move into the AI space, &amp; is very passionate about <a href="https://twitter.com/hashtag/MachineLearning?src=hash&amp;ref_src=twsrc%5Etfw">#MachineLearning</a> &amp; ML. NET <br> <br>Check out his <a href="https://twitter.com/hashtag/PeopleProfile?src=hash&amp;ref_src=twsrc%5Etfw">#PeopleProfile</a>:<br>➡️<a href="https://t.co/nBhJss8sOs">https://t.co/nBhJss8sOs</a> <a href="https://twitter.com/hashtag/MVPBuzz?src=hash&amp;ref_src=twsrc%5Etfw">#MVPBuzz</a> <a href="https://t.co/CluzJPtBTI">pic.twitter.com/CluzJPtBTI</a></p>&mdash; SSW / SSW TV (@SSW_TV) <a href="https://twitter.com/SSW_TV/status/1317996770069147648?ref_src=twsrc%5Etfw">October 19, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`

PS. Requested by @UlyssesMaclaren under **RE: Showing off MVP on JK's people profile**

1. Please action

[AB#58090](https://ssw.visualstudio.com/00f23d37-efb4-45db-8a76-56aba33a8301/_workitems/edit/58090)

**Comment by wicksipedia** [comment]
Hey @SebastienBoissiere 
Have a look at https://github.com/MichaelDeBoey/gatsby-remark-embedder#twitter
It'll allow us to setup the embeds for multiple platforms easily

**Comment by christianmorfordwaitessw** [comment]
Cc: @adamcogan 
Hi @tiagov8,

> 1, We would like to add embedded tweets to SSW People Profiles

**Done** - See https://www.ssw.com.au/people/sample
![image](https://user-images.githubusercontent.com/56522256/121104739-027dd900-c846-11eb-87b5-81ab3350135a.png)
**Figure: Embedding Tweets on SSW.People profiles**
