### ISSUE TITLE
Github Contributions reporting no contributions

### ISSUE THREAD

**Issue by AlexBreskin** [SSWConsulting/SSW.People.Profiles#440]
Contributions are not reporting my contributions
![image](https://user-images.githubusercontent.com/38871792/107310467-99c56080-6ae0-11eb-9f3d-524699bc8042.png)
**Figure: GitHub contributions widget as it appears since 9th of February 2021**

It appears that this is affecting all SSW People profiles

**Comment by christianmorfordwaitessw** [comment]
To: @AlexBreskin 
Cc: @adamcogan 

Hi @AlexBreskin ,

> Contributions are not reporting my contributions

**Done** - See https://www.ssw.com.au/people/alex-breskin
![image](https://user-images.githubusercontent.com/56522256/107460140-a793e800-6bab-11eb-83d2-fc6845912fe1.png)
**Figure: GitHub Contributions chart now working again**
