### ISSUE TITLE
Can we have a new role "Others" for non-dev-manager-design-admins

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People.Profiles#474]
Hi team,

We hired 2 electricians and their profiles are showing at the top of SSW People:
<img width="867" alt="Screen Shot 2021-04-21 at 9 21 28 AM" src="https://user-images.githubusercontent.com/12601228/115588078-35164700-a283-11eb-8984-d5e6fc715684.png">

1. Please create a new category role "Others"
2. Add [Taq](https://www.ssw.com.au/people/taq) and [Chris](https://www.ssw.com.au/people/chris-hoogwerf) under it
3. Show this new section after "Admin" at the bottom
4. Change from "Admin" to "Admins" for consistency

**Comment by christianmorfordwaitessw** [comment]
HI @tiagov8,

> 1. Please create a new category role "Others"
> 2. Add Taq and Chris under it
> 3. Show this new section after "Admin" at the bottom
> 4. Change from "Admin" to "Admins" for consistency

**All Done** - We added a new category "Automation & Electrical" for Taq and Chris
See - https://www.ssw.com.au/people/
![image](https://user-images.githubusercontent.com/56522256/120444299-d89e5f80-c3ca-11eb-994a-7e02cea3c41c.png)
**Figure: New categories created on SSW.People**

-Christian
