### ISSUE TITLE
🐛 BUG - Broken image in wiki

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People.Profiles#584]
Hi team,

there is a broken image here https://github.com/SSWConsulting/SSW.People.Profiles/wiki

1. Please investigate how it got lost
2. Fix the image

<img width="1042" alt="Screen Shot 2022-01-03 at 4 15 20 PM" src="https://user-images.githubusercontent.com/12601228/147970423-ed701ccc-2317-4a12-b4a8-64dccb212754.png">

**Comment by tiagov8** [comment]
UPDATE:

Found 2 more broken images here: https://github.com/SSWConsulting/SSW.People.Profiles/wiki/3.-Updating-CRM

and many more here: https://github.com/SSWConsulting/SSW.People.Profiles/wiki/4.-Creating-profiles

and 1 more at the end of https://github.com/SSWConsulting/SSW.People.Profiles/wiki/Badge-Library

**Comment by christianmorfordwaitessw** [comment]
Hi @tiagov8 

> 1. Please investigate how it got lost

Changes were made to the Wiki but the images had not been merged yet, causing broken links.

> 2. Fix the images

PR has been merged fixing the broken images
