### ISSUE TITLE
BUG: Styling missing on links

### ISSUE THREAD

**Issue by christianmorfordwaitessw** [SSWConsulting/SSW.People.Profiles#588]
To: @christianmorfordwaitessw
Cc: @adamcogan, @tiagov8 

To Myself,

The underlines and red mouseover styling is missing on links
See https://www.ssw.com.au/people/ 

1. Fix the styling on SSW.People

![image](https://user-images.githubusercontent.com/56522256/149420029-b17abfa7-e80f-4fa4-ba7e-a6e36fb31f23.png)
**Figure: Links should be underlined and appear red on hover**

**Comment by christianmorfordwaitessw** [comment]
> 1. Fix the styling on SSW.People

**Done** - See https://www.ssw.com.au/people/
![image](https://user-images.githubusercontent.com/56522256/149461298-4730b309-9871-4be1-becf-779b68fd525e.png)
**Figure: Styling of links fixed on SSW.People**

**Comment by tiagov8** [comment]
cc @bettybondoc 

Hi @christianmorfordwaitessw 

Apparently this is happening again: https://github.com/SSWConsulting/SSW.People/issues/616

I have assigned the new Issue to you ;)
