### ISSUE TITLE
GitHub Contributions section is broken

### ISSUE THREAD

**Issue by KahaMason** [SSWConsulting/SSW.People.Profiles#718]
Hi Team,

It looks like the GitHub contributions section on everyone's profile is broken.

![image](https://user-images.githubusercontent.com/41455076/191384888-df61c437-f42f-41bd-9f4d-2d3731279d6b.png)
**Figure: Broken GitHub Contributions Section**

**Comment by bradystroud** [comment]
Already resolved as part of SSWConsulting/SSW.People#433 🙂
