### ISSUE TITLE
Jean Thirion Content - Reduce Bold

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.People.Profiles#82]
Hi @JeanThirion 
@christoment Chris mentioned that he liked some things bolded for highlights... but that you had gone a little overboard on the bold. I agree. 
1. Please review
-a
![Jean](https://user-images.githubusercontent.com/1222712/78766732-fc376700-79cc-11ea-8ff7-425b8f5e21d0.png)

**Comment by JeanThirion** [comment]
Hey @adamcogan ,

> 1. Please review

I don't think there is too much of it, what do you suggest ? 
https://www.ssw.com.au/people/Jean-Thirion

J

**Comment by UlyssesMaclaren** [comment]
> Hey @adamcogan ,
> 
> > 1. Please review
> 
> I don't think there is too much of it, what do you suggest ?
> https://www.ssw.com.au/people/Jean-Thirion
> 
> J

Maybe just leave the technologies and your job title bold and remove the rest

**Comment by adamcogan** [comment]
5 months... reminder

**Comment by JeanThirion** [comment]
@adamcogan done - https://www.ssw.com.au/people/jean-thirion
